### ISSUE TITLE
new CLONE_TRIGGER function available

### ISSUE THREAD

**Issue by GwendolyneFreddy** [Gibberlings3/transitions#3]
Hello,

Nice to see you being so active. :wink:

At the request of a French modder, I gathered most of my CLONE_TRIGGER functions into a single one that can clone any type of trigger and modify a few parameters before cloning.
Let me know if you are interested in using it.

**Comment by lzenner** [comment]
I'd love to use it.  Merci!

**Comment by GwendolyneFreddy** [comment]
I am still trying to find the best way to modify flags before cloning the trigger. For the moment, I "borrowed" your integer variable to make the function compatible with your mod, but I would prefer to offer the possibility to change flags in a more instinctive way, using BITn arrays. Let me a couple of days to find a solution that will not irritate my nerves before sharing it. :wink:

**Comment by lzenner** [comment]
I wrote a specific one to unlock doors using the bitwise operators.  It is better.  I was just being lazy when I initially modified your library.  Please don't worry about making your library compatible with Transitions.  I will make Transitions compatible with your library.  I'll be starting work on it again soon anyway.  I very much appreciate you allowing me to use it.

**Comment by GwendolyneFreddy** [comment]
Nevermind. I got it:

 STR_VAR  GW_flags_new = "same" // Optional: Flag - default is to use whatever is in the original

All you add to type is BITn pairs (BITm=0;BITn=1).

For example, if you want to remove BIT0 and add BIT11, type

GW_flags_new = "BIT0=0;BIT11=1" The function will automatically modify the flags if needed.

**Comment by GwendolyneFreddy** [comment]
I did not test [it](https://github.com/GwendolyneFreddy/temporary_repo/blob/main/gw_clone_triggers.tpa) intensively since I added the new flags parsing feature, but it worked fine before.

I planned a lot of other settings to add, so feel free to ask if you need something special. :wink:

**Comment by lzenner** [comment]
I forked it.   ...  I don't think I'll ever get used to Git terminology....sounds like I'm being bad.  But thank you very much!  When I go back to Transitions and put in its remaining components, I'll incorporate this.  Again, thank you so much!
